export const SUPABASE_GATEWAY_TAG = "SUPABASE_GATEWAY";
export const SUPABASE_INSTANCE_TAG = "SUPABASE_INSTANCE";
export const CONFIG_GATEWAY_TAG = "CONFIG_GATEWAY";

export const SUPABASE_SDK_ERROR_TAG = "SUPABASE_SDK_ERROR";
